== API Enhancements
There are various small changes. Even if we don't leverage JPMS, once we onboard Java 9, we can make use of these small enhancements immediately.

=== Collection Factories
----
/* Comment sections would break ... */
List<Integer> listOfNumbers = List.of(1, 2, 3, 4, 5
                                        /*, null*/);

Set<Integer> setOfNumbers = Set.of(1, 2, 3, 4, 5/*, 1*/);

Map<String, String> mapOfString =
    Map.of("key1", "value1", "key2", "value2");

Map<String, String> moreMapOfString =
    Map.ofEntries(
        Map.entry("key1", "value1"),
        Map.entry("key2", "value2")/*,
        Map.entry("key1", "value3")*/
);
----
[NOTE.speaker]
--
Collection Factories Create Immutable Collections, they are not just syntactic sugar but also use less memory than that of the other means of Creating Immutable Collections.
--


=== Stream Enhancements
----
Stream.of("a", "b", "c", "", "e")
                .takeWhile(s -> !s.isEmpty())
                .forEach(System.out::print);

Stream.of("a", "b", "c", "de", "f")
                .dropWhile(s -> s.length() <= 1)
                .forEach(System.out::print);

Stream.iterate(1, i -> 2 * i)
                .filter(i->i<=10)
                .forEach(System.out::println);

Stream.iterate(1, i -> i <= 10, i -> 2 * i)
                .forEach(System.out::println);
----

[NOTE.speaker]
--
takewhile, dropwhile, lambdas in iterator are few enhancement made in Stream API.
These methods are also very useful for reactive programming.
--

=== Try with Resource
----
FileReader fileReader 
                  = new FileReader(new File(fileURI));
BufferedReader bufferedReader 
                  = new BufferedReader(fileReader);
try (fileReader; bufferedReader) {

    String line = "";
    while ((line = bufferedReader.readLine()) != null) {
        fileContent =line;
    }
}
----

[NOTE.speaker]
--
Try with Resource was introduced to ensure Auto Resource Managament(ARM).
It was introduced in Java 7, since then to leverage ARM, the resources has to be created with try block. it cannot be created outside it.

Now it has been allowed, but only a final or an effectively final resource object alone can be used with ARM.
--

=== Diamond Operator
----
<T> Box<T> createBox(T content) {
    // we have to put the `T` here :(
    return new Box<T>(content) { };
}

<T> Box<T> createBox(T content) {
    // Java 9 can infer `T` 
    // because it is a denotable type
    return new Box<>(content) { };
}

Box<?> createCrazyBox(Object content) {
    List<?> innerList = Arrays.asList(content);
    // we can't do the following 
    // because the inferred type is non-denotable
    return new Box<List<?>>(innerList) { };
}
----

[NOTE.speaker]
--
Diamond Operators were introduced in Java 7, it tried to remove the mentioning of Type Argument in many places were it can infer from variables / Target Types. In some places like Anonymous class where such inference is apparently possible was not inferrable by Compiler in earlier versions, the compiler now can infer the Type arguments in Anonymous class.

Type Inference is possible only when it can be denotable, usage of unbounded wildcard makes the type to be non denotable, hence in such places diamond operator cannot be used. Beware of such pitfalls!!!
--

=== Deprecated Annotation Enhancement
----
@Deprecated(since = "3.0")
public class Asset {

    @Deprecated(since = "1.0", forRemoval=true)
    public void getAssertValue() {

    }
}
----

[NOTE.speaker]
--

In JDK since denotes the JDK version.
In JDK if for removal is true then the Deprecated Class or method will be removed in next release.

Reference:

http://vojtechruzicka.com/java-9-enhanced-deprecation/
--

=== SafeVarargs
It is now applicable to private non final methods.
----
@SafeVarargs
private <T> Optional<T> privateNonStatic(T... args) {
    if (args.length == 0)
        return Optional.empty();
    else
        return Optional.of(args[0]);
}
----
[NOTE.speaker]
--
SafeVarargs was not applicable to methods which cannot be overriden.
In other words, it is only applicable to static, final methods & constructors.
For no apparent reason, we cannot use them in private non final methods, which also cannot be overriden.
This is fixed in java 9.
--